apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  access: proxy
  isDefault: true
- name: Alertmanager
  type: alertmanager
  url: http://alert-manager:9093
  access: proxy
  jsonData:  
    implementation: prometheus
    handleGrafanaManagedAlerts: false