scrape_configs:
  ##### Prometheus server #####
  - job_name: "monitor-cluster"
    static_configs:
      - targets: ["prometheus:9090"]
        labels:
          hostname: PrometheusProd
          type: docker
      # - targets: ["alert-manager:9093"]
      #   labels:
      #     hostname: Alert-manager
      #     type: docker

  - job_name: 'micro-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:9211', 'host.docker.internal:9212', 'host.docker.internal:9213', 'host.docker.internal:9214' ]

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:9211' ]

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:9212' ]

  - job_name: 'payment-proccessing-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:9213' ]

  - job_name: 'profile-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:9214' ]

