services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert-rules:/etc/prometheus/rules
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d # Giữ lại dữ liệu trong 15 ngày
      - --storage.tsdb.path=data/ # Lưu trữ dữ liệu trong thư mục data
    networks:
      - webflux-kafka

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    env_file:
      - .grafana.secret
    networks:
      - webflux-kafka

  alert-manager:
    image: prom/alertmanager
    container_name: alert-manager
    ports:
      - "9095:9093"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./alertmanager:/etc/alertmanager
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    networks:
      - webflux-kafka

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - webflux-kafka

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - webflux-kafka

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - webflux-kafka
  
  tempo:
    image: grafana/tempo
    container_name: tempo
    ports:
      - "3200:3200"   # Tempo UI/API
      - "9411:9411"   # Zipkin receiver (trace input)
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./tempo/tempo.yml:/etc/tempo.yaml
    networks:
      - webflux-kafka

  # kafka-exporter:
  #   image: bitnami/kafka-exporter:1.7.0
  #   ports:
  #     - "9308:9308"
  #   environment:
  #     - KAFKA_SERVER=kafka1:9092
  #   networks:
  #     - webflux-kafka

      
networks:
  webflux-kafka:
    external: true
