services:
  mysql:
    image: mysql:8.3.0
    container_name: weblux-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - webflux-kafka

volumes:
  mysql-data:

networks:
  webflux-kafka:
    external: true
